name: Build mpv on MacOS

on: [workflow_dispatch]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: brew install yasm nasm pkg-config libass ffmpeg create-dmg
        
      - name: Build
        run: |
            ./bootstrap.py
            ./waf configure
            ./waf
            TOOLS/osxbundle.py build/mpv

      - name: Build package
        run: |
            mkdir release
            cp -r build/mpv.app release
            #create-dmg --sandbox-safe --no-internet-enable --volname "mpv" --app-drop-link 200 185 mpv.dmg release
            #rm -rf release/mpv.app
            #mv mpv.dmg release/
            cd release
            tar -cjf mpv-bin.tar.bz2 *

      - name: Create artifact
        #if: ${{ false }}
        uses: actions/upload-artifact@v2
        with:
          name: mpv-bin.tar.bz2
          path: ./release/mpv-bin.tar.bz2
